name: photo_tune_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  image_picker: ^1.1.0
  dotted_border: ^2.1.0
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.5
  before_after: ^3.0.0+1
  path_provider: ^2.1.3
##  open_file: ^3.3.2
##  media_store_plus: ^0.1.1
##  open_filex: ^4.4.0
##  external_path: ^1.0.3
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  image: ^4.1.7
  replicate: ^1.0.0
  flutter_dotenv: ^5.1.0
  http: ^0.13.6
  pretty_dio_logger: ^1.3.1
  dio: ^5.4.3+1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - .env
